### ISSUE TITLE
SME feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-google#13]
- [x] You will use GKE with a Google Container Registry -> should this be, “In this guide, you will…”
- [ ] fees may be associated with running this guide.  -> do we not have an alternative for people that don’t want to pay?
- [ ] If you do not have any projects on your account, you will be prompted to create one. Otherwise, select the option to create a new project. -> do we need this second sentence?
- [x] ject ID is available to use, you see the following output: -> “you should see” or “you will see”, I think this needs another word
- [x] where the resources for your cloud deployments will be hosted on. -> do we need the “on” at the end?
- [x] See the list of available zones and its corresponding regions for your project: -> for consistency should this not have “Run the following command to see” at the start like the other times in the document?
- [x] You see an output similar to the following: -> should this not be “you should see” or “you will see” for every instance of this?
- [x] or using an Ingress -> “or using Ingress”, do we need the “an”?

**Comment by gkwan-ibm** [comment]
@GraceJansen ^

**Comment by NimG98** [comment]
> “or using Ingress”, do we need the “an”?

- I think the proper usage is `an Ingress` and not just `Ingress`.
Based off of usage in other [articles](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer#step_3_create_an_ingress_resource).

> fees may be associated with running this guide. -> do we not have an alternative for people that don’t want to pay?

- They do have a free trial, but since Google can change their pricing policies at any time and we should not be providing any details of their pricing, we don't mention the free trial.
- But, there is a link in the guide https://console.cloud.google.com/getting-started, and at the top of the link, the users would see the button that says “Try for free”.

> If you do not have any projects on your account, you will be prompted to create one. Otherwise, select the option to create a new project. -> do we need this second sentence?

- The second sentence is for when the user already has projects. We want them to select the option that says "Create a new project" instead of using an existing project.

- In the first sentence, users who don't have any projects, they get directly asked to make a new project and have to answer yes or no.

- Is this a better way to word it?
    > If you do not have any projects on your account, you will be automatically prompted to create one.
Otherwise, select the "Create a new project" option.

**Comment by NimG98** [comment]
Changed create a project sentence to:

> Create a new project for your guide. 
You will be prompted to do so if you have no projects in your account.
